name: Jest Tests

on: [push]
env: [go-rewrite]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: alchemy
          POSTGRES_PASSWORD: alchemy
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.7
    - run: npm ci
    - run: go test -v
      env:
        CI: true
        DATABASE_URL: postgres://alchemy:alchemy@postgres:5432/alchemy
        APP_DB_USERNAME: alchemy
        APP_DB_PASSWORD: alchemy
        APP_DB_NAME: postgres
        APP_DB_HOST: postgres
        PORT: 7890
